# This is a basic workflow to help you get started with Actions
# File: .github/workflows/ci.yml

name: CI and Dependabot Updates

on:
  # Trigger workflow on code changes
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Trigger workflow on Dependabot pull requests

    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: macos-latest # Use macOS environment

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Specify your desired Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest --disable-warnings

  dependabot-check:
    # Ensure this runs only for Dependabot PRs
    if: github.actor == 'dependabot[bot]'
    runs-on: macos-latest # Use macOS environment

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

